package main

const suffix = "_msg_gen"

// tpl temp
const tpl = `
// Code generated by github.com/pwli0755/errcodegen DO NOT EDIT
// Package {{.pkg}} const code comment msg
package {{.pkg}}

// messages get msg from const comment
var messages = map[{{.constType}}]string{
	{{range $key, $value := .comments}}
	{{$key}}: "{{$value}}",{{end}}
}
{{ if ne .constType "int" }}
// String return string
func (code int) String () string {
	return GetMsg(code)
}
{{ end }}
// GetMsg get error msg
func GetMsg(code {{.constType}}) string {
	if msg, ok := messages[code]; ok {
		return msg
	}
	return "UNKNOWN ERROR"
}
`
